baseurl = "/"
languageCode = "en-us"
title = "Okkur - Syna!"
themesDir = "themes"
theme = "syna"
enableGitInfo = true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
ignorefiles = ["content/dev/.*"]

[params]
debug = true
description = "Open Source Theme for your next project"
name = "Okkur Labs"
unsafeEvents = true

[params.colors]
danger = "#dc1200"
dark = "#343a40"
info = "#00c9dc"
light = "#f8f9fa"
primary = "#00838F"
secondary = "#868e96"
success = "#008f54"
warning = "#fdf314"

[params.custom]
favicon_ico_sizes = "16x16 32x32"
favicon_png = "favicon.png"
favicon_svg = "favicon.svg"

[params.fontawesome]
disabled = false
pro = false

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[outputs]
home = ["HTML", "JSON"]