baseurl = "/"
languageCode = "en-us"
title = "Gaudimonium"
themesDir = "themes"
theme = "learn"
enableGitInfo = true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
ignorefiles = ["content/dev/.*"]

[params]
debug = true
description = "The project known as Project Gaudimonium"
name = "Project Gaudimonium"
unsafeEvents = false

[params.colors]
danger = "#dc1200"
dark = "#343a40"
info = "#00c9dc"
light = "#f8f9fa"
primary = "#00838F"
secondary = "#868e96"
success = "#008f54"
warning = "#fdf314"

[params.custom]
favicon = "images/favicon.ico"
favicon_ico_sizes = "16x16 32x32 64x64"
favicon_png = "images/favicon.png"
favicon_svg = "images/favicon.svg"

[params.fontawesome]
disabled = false
pro = false

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[outputs]
home = ["HTML", "JSON"]